### ISSUE TITLE
Dimension out of range error, have tried it with various versions of torch

### ISSUE THREAD

**Issue by ghost** [VinAIResearch/XPhoneBERT#11]
-- Process 0 terminated with the following error:
Traceback (most recent call last):
  File "/home/jumpcloud/miniconda3/envs/vits/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 69, in _wrap
    fn(i, *args)
  File "/home/jumpcloud/libraries/XPhoneBERT/VITS_with_XPhoneBERT/train.py", line 130, in run
    train_and_evaluate(rank, epoch, hps, [net_g, net_d], [optim_g, optim_d], [scheduler_g, scheduler_d], scaler,
  File "/home/jumpcloud/libraries/XPhoneBERT/VITS_with_XPhoneBERT/train.py", line 152, in train_and_evaluate
    for batch_idx, (x, attention_mask, x_lengths, spec, spec_lengths, y, y_lengths) in enumerate(train_loader):
  File "/home/jumpcloud/miniconda3/envs/vits/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 628, in __next__
    data = self._next_data()
  File "/home/jumpcloud/miniconda3/envs/vits/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1333, in _next_data
    return self._process_data(data)
  File "/home/jumpcloud/miniconda3/envs/vits/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1359, in _process_data
    data.reraise()
  File "/home/jumpcloud/miniconda3/envs/vits/lib/python3.8/site-packages/torch/_utils.py", line 543, in reraise
    raise exception
IndexError: Caught IndexError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/jumpcloud/miniconda3/envs/vits/lib/python3.8/site-packages/torch/utils/data/_utils/worker.py", line 302, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/jumpcloud/miniconda3/envs/vits/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 61, in fetch
    return self.collate_fn(data)
  File "/home/jumpcloud/libraries/XPhoneBERT/VITS_with_XPhoneBERT/data_utils.py", line 115, in __call__
    torch.LongTensor([x[2].size(1) for x in batch]),
  File "/home/jumpcloud/libraries/XPhoneBERT/VITS_with_XPhoneBERT/data_utils.py", line 115, in <listcomp>
    torch.LongTensor([x[2].size(1) for x in batch]),
IndexError: Dimension out of range (expected to be in range of [-1, 0], but got 1)

**Comment by thelinhbkhn2014** [comment]
I do not know why you got this error. It might be because of the environment. You can check and install all libraries like our requirements (https://github.com/VinAIResearch/XPhoneBERT/blob/main/VITS_with_XPhoneBERT/requirements.txt)
